const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
const SET_FEATURED_PRODUCTS = 'SET_FEATURED_PRODUCTS';
const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
const SET_CURRENT_PRODUCT_REVIEW = 'SET_CURRENT_PRODUCT_REVIEW';
const UPDATE_CART = 'UPDATE_CART';
const ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT';

export {
  SET_ALL_PRODUCTS,
  UPDATE_CART,
  ADMIN_DELETE_PRODUCT,
  SET_CURRENT_PRODUCT,
  SET_CURRENT_PRODUCT_REVIEW,
  SET_FEATURED_PRODUCTS,
};
