export const AUTH_SUCCESS_GOOGLE = 'AUTH_SUCCESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const ADMIN_SAVE_ALL_USERS = 'ADMIN_SAVE_ALL_USERS';
export const ADMIN_DELETE_USER = 'ADMIN_DELETE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
